version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: grievance_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grievance-backend:
    build: .
    container_name: grievance-app
    ports:
      - "10000:10000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: jdbc:mysql://root:daNzbukvRMNOHTRrvJkpIOvxKmLtikeD@caboose.proxy.rlwy.net:15913/railway
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: daNzbukvRMNOHTRrvJkpIOvxKmLtikeD
      PORT: 10000
    restart: always

volumes:
  mysql_data:
